### ISSUE TITLE
Contribution 

### ISSUE THREAD

**Issue by Pandz18** [ThusharaX/Cpp-programming#2]
Hey , I would like to contribute to your repo , where should I store the files ? And should I make 1 single program file consisting of many classes for the different programs or should I create seperate files for each type of program

cheers

**Comment by ThusharaX** [comment]
Hello, Thank you for your interest.
This repository is designed for beginner level C++ **Questions and Answers**.
So I think it would be ok to create a separate folder called `Extra Questions` and put the questions in it in order.
Put the code for the same question in the same folder.
Make sure to rename it properly.

**Comment by Pandz18** [comment]
Hey , 
Awesome , will keep that in mind , cheers 

Also I might be busy for the next three months due to personal reasons , so I apologise in advance for my lack of activity

**Comment by ThusharaX** [comment]
Thank you for your contribution 💕

**Comment by ThusharaX** [comment]
Thank you for your contribution 💕

**Comment by Pandz18** [comment]
> Thank you for your contribution 💕

Hey  , Don’t mention it , that’s what Open Sourcing is all about 😄 ❤️
