### ISSUE TITLE
Use your repository for a blog 

### ISSUE THREAD

**Issue by ghost** [ThusharaX/Cpp-programming#7]
Hey , I wanted to make a blog and was wondering with your permission if I could use your Repository as examples ?

I will show your name as well as link your repository so for anyone interested can contribute too .

I shall only do so , once you give me the ok for sharing your repository .

**Comment by ThusharaX** [comment]
> Hey , I wanted to make a blog and was wondering with your permission if I could use your Repository as examples ?
> 
> I will show your name as well as link your repository so for anyone interested can contribute too .
> 
> 
> I shall only do so , once you give me the ok for sharing your repository .

No problem.

Use these as examples in your blog.
But it is better not to publish some of the PDFs and pictures contained herein in that blog.
Also don't forget to send me the link of your blog 😁😇

**Comment by Pandz18** [comment]
sure man , thank you , cheers
